## Quorum Settings ##
#
# DO NOT edit this file directly. To configure Quorum edit
# config/quorum_settings.yml.

## Load Quorum Blast Setttings ##
blast = YAML.load_file(
  "#{::Rails.root.to_s}/config/quorum_settings.yml"
)[::Rails.env.to_s]['blast']

# Sub %{RAILS_ROOT}
blast.each_value do |v| 
  if v.kind_of?(String)
    v.to_s.gsub!('%{RAILS_ROOT}', ::Rails.root.to_s)
  end
end

Quorum.blast_remote      = blast['remote']
Quorum.blast_ssh_host    = blast['ssh_host']
Quorum.blast_ssh_user    = blast['ssh_user']
Quorum.blast_ssh_options = blast['ssh_options']
Quorum.blast_script      = blast['script']
Quorum.blast_log_dir     = blast['log_dir']
Quorum.blast_tmp_dir     = blast['tmp_dir']
Quorum.blast_db          = blast['blast_db']
Quorum.tblastn           = blast['tblastn']
Quorum.blastp            = blast['blastp']
Quorum.blastn            = blast['blastn']
Quorum.blastx            = blast['blastx']
Quorum.blast_threads     = blast['blast_threads']
## End Blast Settings ##

## Load Quorum Hmmer Setttings ##
hmmer = YAML.load_file(
  "#{::Rails.root.to_s}/config/quorum_settings.yml"
)[::Rails.env.to_s]['hmmer']

# Sub %{RAILS_ROOT}
hmmer.each_value do |v| 
  if v.kind_of?(String)
    v.to_s.gsub!('%{RAILS_ROOT}', ::Rails.root.to_s)
  end
end

Quorum.hmmer_remote      = hmmer['remote']
Quorum.hmmer_ssh_host    = hmmer['ssh_host']
Quorum.hmmer_ssh_user    = hmmer['ssh_user']
Quorum.hmmer_ssh_options = hmmer['ssh_options']
Quorum.hmmer_script      = hmmer['script']
Quorum.hmmer_log_dir     = hmmer['log_dir']
Quorum.hmmer_tmp_dir     = hmmer['tmp_dir']
Quorum.hmmer_db          = hmmer['hmmer_db']
Quorum.hmmer_threads     = hmmer['hmmer_threads']
## End Hmmer Settings ##

