## Quorum Settings ##
#
# DO NOT edit this file directly. To configure Quorum edit
# config/quorum_settings.yml.

## Load Quorum Setttings ##
settings = YAML.load_file(
  "#{::Rails.root.to_s}/config/quorum_settings.yml"
)[::Rails.env.to_s]

## Sub %{RAILS_ROOT} ##
settings.keys.each do |k|
  if settings[k.to_s].respond_to?(:each_value)
    settings[k.to_s].each_value do |v|
      if v.kind_of?(String)
        v.to_s.gsub!('%{RAILS_ROOT}', ::Rails.root.to_s)
      end
    end
  else
    if settings[k.to_s].kind_of?(String)
      settings[k.to_s].gsub!('%{RAILS_ROOT}', ::Rails.root.to_s)
    end
  end
end

## Quorum General Settings ##
Quorum.max_sequence_size = settings['max_sequence_size']

## Quorum GMAP Settings ##
gmap = settings['gmap']

Quorum.gmap_remote                  = gmap['remote']
Quorum.gmap_ssh_host                = gmap['ssh_host']
Quorum.gmap_ssh_user                = gmap['ssh_user']
Quorum.gmap_ssh_options             = gmap['ssh_options']
Quorum.gmap_bin                     = gmap['bin']
Quorum.gmap_log_dir                 = gmap['log_dir']
Quorum.gmap_tmp_dir                 = gmap['tmp_dir']
Quorum.gmap_db_dir                  = gmap['gmap_db_dir']
Quorum.gmap_db                      = gmap['gmap_db']
Quorum.gmap_max_internal_intron_len = gmap['gmap_max_internal_intron_len']
Quorum.gmap_max_total_intron_len    = gmap['gmap_max_total_intron_len']
Quorum.gmap_threads                 = gmap['gmap_threads']

## Quorum Blast Settings ##
blast = settings['blast']

Quorum.blast_remote      = blast['remote']
Quorum.blast_ssh_host    = blast['ssh_host']
Quorum.blast_ssh_user    = blast['ssh_user']
Quorum.blast_ssh_options = blast['ssh_options']
Quorum.blast_bin         = blast['bin']
Quorum.blast_log_dir     = blast['log_dir']
Quorum.blast_tmp_dir     = blast['tmp_dir']
Quorum.blast_db          = blast['blast_db']
Quorum.tblastn           = blast['tblastn']
Quorum.blastp            = blast['blastp']
Quorum.blastn            = blast['blastn']
Quorum.blastx            = blast['blastx']
Quorum.blast_threads     = blast['blast_threads']
