## Quorum Settings ##
#
# DO NOT edit this file directly. To configure Quorum edit
# config/quorum_settings.yml.

# Load Quorum Blast Setttings
blast = YAML.load_file(
  "#{::Rails.root.to_s}/config/quorum_settings.yml"
)[::Rails.env.to_s]['blast']

# Sub %{RAILS_ROOT}
blast.each_value do |v| 
  if v.kind_of?(String)
    v.to_s.gsub!('%{RAILS_ROOT}', ::Rails.root.to_s)
  end
end

Quorum.blast_remote      = blast['remote']
Quorum.blast_ssh_host    = blast['ssh_host']
Quorum.blast_ssh_user    = blast['ssh_user']
Quorum.blast_ssh_options = blast['ssh_options']
Quorum.blast_script      = blast['script']
Quorum.blast_log_dir     = blast['log_dir']
Quorum.blast_tmp_dir     = blast['tmp_dir']
Quorum.blast_db          = blast['blast_db']
Quorum.tblastn           = blast['tblastn']
Quorum.blastp            = blast['blastp']
Quorum.blastn            = blast['blastn']
Quorum.blastx            = blast['blastx']
Quorum.blast_threads     = blast['blast_threads']
## End Blast Settings ##
